#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
#
Name     : QXlsx
Version  : 1.4.6
Release  : 1
URL      : https://github.com/QtExcel/QXlsx/archive/v1.4.6/QXlsx-1.4.6.tar.gz
Source0  : https://github.com/QtExcel/QXlsx/archive/v1.4.6/QXlsx-1.4.6.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT MPL-2.0
Requires: QXlsx-lib = %{version}-%{release}
Requires: QXlsx-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# QXlsx
<p align="center"><img src="https://raw.githubusercontent.com/QtExcel/QXlsx/master/markdown.data/QXlsx-Desktop.png"></p>

%package dev
Summary: dev components for the QXlsx package.
Group: Development
Requires: QXlsx-lib = %{version}-%{release}
Provides: QXlsx-devel = %{version}-%{release}
Requires: QXlsx = %{version}-%{release}

%description dev
dev components for the QXlsx package.


%package lib
Summary: lib components for the QXlsx package.
Group: Libraries
Requires: QXlsx-license = %{version}-%{release}

%description lib
lib components for the QXlsx package.


%package license
Summary: license components for the QXlsx package.
Group: Default

%description license
license components for the QXlsx package.


%prep
%setup -q -n QXlsx-1.4.6
cd %{_builddir}/QXlsx-1.4.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689725942
pushd QXlsx
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%cmake ..
make  %{?_smp_mflags}
popd
popd

%install
export SOURCE_DATE_EPOCH=1689725942
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/QXlsx
cp %{_builddir}/QXlsx-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/QXlsx/0fc052f0f02f09fd3d64d63ab5deed0ebcbb0ba7 || :
cp %{_builddir}/QXlsx-%{version}/Pump/xlsx_files/License.txt %{buildroot}/usr/share/package-licenses/QXlsx/ddc5f49c0c88da977ac099ee6e7f251c5cdc95be || :
pushd QXlsx
pushd clr-build
%make_install
popd
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/QXlsxQt5/xlsxabstractooxmlfile.h
/usr/include/QXlsxQt5/xlsxabstractsheet.h
/usr/include/QXlsxQt5/xlsxabstractsheet_p.h
/usr/include/QXlsxQt5/xlsxcell.h
/usr/include/QXlsxQt5/xlsxcellformula.h
/usr/include/QXlsxQt5/xlsxcelllocation.h
/usr/include/QXlsxQt5/xlsxcellrange.h
/usr/include/QXlsxQt5/xlsxcellreference.h
/usr/include/QXlsxQt5/xlsxchart.h
/usr/include/QXlsxQt5/xlsxchartsheet.h
/usr/include/QXlsxQt5/xlsxconditionalformatting.h
/usr/include/QXlsxQt5/xlsxdatavalidation.h
/usr/include/QXlsxQt5/xlsxdatetype.h
/usr/include/QXlsxQt5/xlsxdocument.h
/usr/include/QXlsxQt5/xlsxformat.h
/usr/include/QXlsxQt5/xlsxglobal.h
/usr/include/QXlsxQt5/xlsxrichstring.h
/usr/include/QXlsxQt5/xlsxworkbook.h
/usr/include/QXlsxQt5/xlsxworksheet.h
/usr/lib64/cmake/QXlsxQt5/QXlsxQt5Config.cmake
/usr/lib64/cmake/QXlsxQt5/QXlsxQt5ConfigVersion.cmake
/usr/lib64/cmake/QXlsxQt5/QXlsxQt5Targets-relwithdebinfo.cmake
/usr/lib64/cmake/QXlsxQt5/QXlsxQt5Targets.cmake
/usr/lib64/libQXlsxQt5.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libQXlsxQt5.so.0.1.4.4
/usr/lib64/libQXlsxQt5.so.1.4.4

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/QXlsx/0fc052f0f02f09fd3d64d63ab5deed0ebcbb0ba7
/usr/share/package-licenses/QXlsx/ddc5f49c0c88da977ac099ee6e7f251c5cdc95be
